### PR TITLE
i18n: adds Italian locale

### PR DESCRIPTION
**Pull request by LeoSpyke**
Adds the Italian locale to the UI as per #47.

### CODE REVIEW

**Comment by cedricve** [comment]
Wonderful work here! I'm going through your PR ASAP @LeoSpyke

**Comment by LeoSpyke** [comment]
@cedricve the translation is complete.

@andp97 are you available for a review?

**Comment by cedricve** [comment]
looks great thank you @LeoSpyke !

**Comment by andp97** [comment]
> @andp97 are you available for a review?
> 
> 

Sorry, I missed it!🥲

**Comment by cedricve** [comment]
No worries it's currently released, but feel free to verify 🗡️

**Pull request merged**
